//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoSlang
{
    public partial class CommunityChat
    {
        protected System.Web.UI.HtmlControls.HtmlAnchor lnkDashboard;
        protected System.Web.UI.HtmlControls.HtmlAnchor lnkDashboard2;
        protected System.Web.UI.WebControls.Panel pnlMemberNav;
        protected System.Web.UI.WebControls.Panel pnlBuddyNav;
        protected System.Web.UI.WebControls.Panel pnlAdminNav;
        protected System.Web.UI.WebControls.Panel pnlNoMessages;
        protected System.Web.UI.WebControls.Repeater rptMessages;
        protected System.Web.UI.WebControls.TextBox txtMessage;
        protected System.Web.UI.WebControls.Button btnSend;
    }
}
