//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoSlang
{
    public partial class ManageUsers
    {
        protected System.Web.UI.WebControls.TextBox txtSearch;
        protected System.Web.UI.WebControls.DropDownList ddlRoleFilter;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.HiddenField hfBanUserId;
        protected System.Web.UI.WebControls.Button btnBanUser;
        protected System.Web.UI.WebControls.Repeater rptUsers;
        protected System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
