//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoSlang
{
    public partial class ManageAvailability
    {
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteId;
        protected global::System.Web.UI.WebControls.HiddenField hfEditId;
        protected global::System.Web.UI.WebControls.HiddenField hfRepeat;
        protected global::System.Web.UI.WebControls.Button btnDeleteConfirm;
        protected global::System.Web.UI.WebControls.Button btnEditConfirm;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.TextBox txtTime;
        protected global::System.Web.UI.WebControls.DropDownList ddlDuration;
        protected global::System.Web.UI.WebControls.Button btnAddSlot;
    }
}
