//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoSlang
{
    public partial class ManageContent
    {
        // Hidden fields
        protected System.Web.UI.WebControls.HiddenField hfActiveTab;
        protected System.Web.UI.WebControls.HiddenField hfSlangID;
        protected System.Web.UI.WebControls.HiddenField hfQuestionID;
        protected System.Web.UI.WebControls.HiddenField hfCurrentModuleOrder;

        // Dictionary
        protected System.Web.UI.WebControls.Panel pnlWordForm;
        protected System.Web.UI.WebControls.Label lblWordFormTitle;
        protected System.Web.UI.WebControls.TextBox txtWord;
        protected System.Web.UI.WebControls.TextBox txtPronunciation;
        protected System.Web.UI.WebControls.DropDownList ddlPartOfSpeech;
        protected System.Web.UI.WebControls.TextBox txtMeaning;
        protected System.Web.UI.WebControls.TextBox txtFullExplanation;
        protected System.Web.UI.WebControls.TextBox txtExampleSentence;
        protected System.Web.UI.WebControls.TextBox txtExampleTranslation;
        protected System.Web.UI.WebControls.DropDownList ddlLevel;
        protected System.Web.UI.WebControls.Repeater rptDictionary;
        protected System.Web.UI.WebControls.Panel pnlDictionaryEmpty;

        // Module Questions
        protected System.Web.UI.WebControls.DropDownList ddlModule;
        protected System.Web.UI.WebControls.Panel pnlQuestionSection;
        protected System.Web.UI.WebControls.Label lblQuestionsFor;
        protected System.Web.UI.WebControls.Panel pnlModule1Note;
        protected System.Web.UI.WebControls.Panel pnlQuestionList;
        protected System.Web.UI.WebControls.Button btnShowAddQuestion;
        protected System.Web.UI.WebControls.Repeater rptQuestions;
        protected System.Web.UI.WebControls.Panel pnlQuestionsEmpty;
        protected System.Web.UI.WebControls.Panel pnlQuestionForm;
        protected System.Web.UI.WebControls.Label lblQuestionFormTitle;
        protected System.Web.UI.WebControls.TextBox txtQuestionNumber;
        protected System.Web.UI.WebControls.DropDownList ddlQuestionType;
        protected System.Web.UI.WebControls.TextBox txtQuestionText;
        protected System.Web.UI.WebControls.TextBox txtOptionA;
        protected System.Web.UI.WebControls.TextBox txtOptionB;
        protected System.Web.UI.WebControls.TextBox txtOptionC;
        protected System.Web.UI.WebControls.TextBox txtOptionD;
        protected System.Web.UI.WebControls.TextBox txtCorrectAnswer;
        protected System.Web.UI.WebControls.TextBox txtExplanation;
    }
}
