//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoSlang
{
    public partial class SessionHistory
    {
        protected global::System.Web.UI.WebControls.HiddenField hfCancelId;
        protected global::System.Web.UI.WebControls.Button btnCancelConfirm;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
