//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoSlang
{
    public partial class SuggestSlang
    {
        protected System.Web.UI.HtmlControls.HtmlAnchor lnkDashboard;
        protected System.Web.UI.HtmlControls.HtmlAnchor lnkDashboard2;
        protected System.Web.UI.WebControls.Literal litSuccess;
        protected System.Web.UI.WebControls.TextBox txtWord;
        protected System.Web.UI.WebControls.TextBox txtPronunciation;
        protected System.Web.UI.WebControls.DropDownList ddlPartOfSpeech;
        protected System.Web.UI.WebControls.TextBox txtMeaning;
        protected System.Web.UI.WebControls.TextBox txtFullExplanation;
        protected System.Web.UI.WebControls.TextBox txtExampleSentence;
        protected System.Web.UI.WebControls.TextBox txtExampleTranslation;
        protected System.Web.UI.WebControls.DropDownList ddlLevel;
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.Repeater rptSuggestions;
        protected System.Web.UI.WebControls.Panel pnlNoSuggestions;
    }
}
