//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoSlang
{
    public partial class WithdrawEarnings
    {
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkLogo;
        protected global::System.Web.UI.WebControls.HiddenField hdnPaymentMethod;
        protected global::System.Web.UI.WebControls.TextBox txtAmount;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
